# Generated by Django 5.1.4 on 2025-01-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
